accounts/urls.py
from django.urls import path
from .views import (
    SignUpView, SigninView,
    logout_view, customer_profile_view,
    OrdersView, order_items_view,
    addresses_view, ChangePasswordView,
    DeleteUserAddress,
)

app_name = 'accounts'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SigninView.as_view(), name='sign_in'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('logout/', logout_view, name='logout'),
    path('profile/', customer_profile_view, name='profile'),
    path('addresses/', addresses_view, name='addresses'),
    path('delete_address/<int:pk>/', DeleteUserAddress.as_view(), name='delete_address'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order_items/<int:order_id>/', order_items_view, name='order_items'),

]

orders/api/urls.py
from django.urls import path
from .views import offer_code_api_view

urlpatterns = [
    path('offer_code/', offer_code_api_view, name='offer_code_api'),
]

orders/urls.py
from django.urls import path

from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'orders'

urlpatterns = [
    path('basket/', basket_view, name='basket'),
    path('basket/delete/', delete_item_from_basket, name='delete_item_from_basket'),
    path('checkout/', checkout, name='checkout'),
]

shopify/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shopify import settings
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, )

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social_django.urls', namespace='social')),

    path('api/v1/', include('core.api.urls')),
    path('', include('products.urls')),
    path('customer/', include('accounts.urls', namespace='customers')),
    path('order/', include('orders.urls')),

    # Django urls for reset password
    path('password_reset/',
         PasswordResetView.as_view(template_name='customers/password_reset.html'),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='customers/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='customers/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(template_name='customers/password_reset_complete.html'),
         name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator

from shopify import settings


class Customer(AbstractUser):
    phone_number_regex = RegexValidator(regex=r"^\+?1?\d{8,15}$", message=_('Must enter a valid phone number'))
    phone_number = models.CharField(validators=[phone_number_regex], max_length=16, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = _("customers")
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        return f'{self.first_name}{self.last_name}'


class Address(models.Model):
    HOME = 'home'
    OFFICE = 'office'
    OTHER = 'other'
    ADDRESS_TYPE = [(HOME, _('Home')), (OFFICE, _('Office')), (OTHER, _('Other')), ]

    # Users can have one or many addresses
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(_("Address"), max_length=1024, )
    country = models.CharField(_("Country"), max_length=30, )
    state = models.CharField(_("State"), max_length=150, )
    city = models.CharField(_("City"), max_length=150, )
    postcode = models.CharField(_("Postcode"), max_length=12, )
    address_type = models.CharField(max_length=6, choices=ADDRESS_TYPE, default=HOME)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    class Meta:
        db_table = _("addresses")
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

    def __str__(self):
        return f'{self.address}'

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from shopify import settings
from accounts.models import Address
from products.models import Product
from djmoney.models.fields import MoneyField


class Discount(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                 related_name='discounts')
    created = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField()
    amount = models.PositiveSmallIntegerField()
    code = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = _('discounts')
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')

    def __str__(self):
        return f'{self.customer} {self.amount}%'


class OrderItem(models.Model):
    product_name = models.CharField(max_length=150)
    quantity = models.SmallIntegerField()

    class Meta:
        db_table = _('order_item ')
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

    def __str__(self):
        return f'{self.product_name}'


class Order(models.Model):
    READY_TO_SHIP = 'ready_to_ship'
    SENDING = 'sending'
    SENT = 'sent'
    STATUS = [
        (READY_TO_SHIP, _('ready_to_ship')),
        (SENDING, _('sending')),
        (SENT, _('sent')),
    ]

    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='orders')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    products = models.ManyToManyField(OrderItem)
    status = models.CharField(
        max_length=15,
        choices=STATUS,
        default=READY_TO_SHIP,
    )
    delivery_method = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    discount = models.OneToOneField(Discount, on_delete=models.RESTRICT, null=True, blank=True)
    total_price_with_discount = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True,
                                           null=True)

    class Meta:
        db_table = _('orders')
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'{self.customer}'

orders/api/views.py
from django.utils.timezone import now
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from orders.models import Discount


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def offer_code_api_view(request):
    if request.method == 'POST':
        offer_code = request.POST.get('offerCode')
        customer = request.user
        try:
            discount = Discount.objects.get(code=offer_code)

            if discount.is_active and discount.expire_date > now() and discount.customer == customer:
                content = {'applied': 'Your discount code was applied correctly.',
                           'amount': discount.amount}
                discount.is_active = False
                discount.save()
                return Response(content, status=status.HTTP_200_OK)

            elif not discount.is_active:
                content = {'used': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

            elif discount.expire_date < now():
                content = {'expired': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

        except Discount.DoesNotExist:
            content = {'incorrect offer code': 'Your offer code is incorrect.'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)

orders/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import Address
from orders.models import Discount, Order
from products.models import Product


def basket_view(request):
    """
    Provides the ability to add products to the basket as well as view the basket
    """
    context = dict()
    if request.method == 'GET':

        if request.session.get('basket'):
            basket = request.session.get('basket')
            product_names = basket.keys()
            context['products_in_basket'] = Product.objects.filter(name__in=product_names)
            return render(request, 'orders/basket.html', context)
        else:
            # Empty basket
            return render(request, 'orders/basket.html')

    product_name = request.POST.get('product_name')
    product_quantity = request.POST.get('product_quantity')

    if not request.session.get('basket'):
        number_of_products_is_stock = Product.objects.get(name=product_name).number_of_product
        if int(product_quantity) > number_of_products_is_stock or int(product_quantity) > 100:
            messages.error(request, 'More than inventory.')
            # Empty basket
            return render(request, 'orders/basket.html')

        # Adding product to the basket for the first time
        request.session['basket'] = {
            product_name: product_quantity
        }
        context['products_in_basket'] = Product.objects.filter(name=product_name)
        return render(request, 'orders/basket.html', context)

    else:
        # Update the basket or add new items to the basket
        basket = request.session.get('basket')
        number_of_products_is_stock = Product.objects.get(name=product_name).number_of_product

        if int(product_quantity) > number_of_products_is_stock or int(product_quantity) > 100:
            product_names = basket.keys()
            messages.error(request, 'More than inventory.')
            context['products_in_basket'] = Product.objects.filter(name__in=product_names)
            return render(request, 'orders/basket.html', context)

        # Add new item to basket
        basket[product_name] = product_quantity
        request.session.modified = True
        product_names = basket.keys()
        messages.success(request, 'Your basket has been updated.')
        context['products_in_basket'] = Product.objects.filter(name__in=product_names)
        return render(request, 'orders/basket.html', context)


def delete_item_from_basket(request):
    """
    Takes the product ID and removes it from the basket
    """
    if request.method == 'POST':
        product_name = Product.objects.get(pk=request.POST.get('productId'))
        basket = request.session.get('basket')
        basket.pop(str(product_name))
        request.session.modified = True
        return HttpResponse('Item deleted')


@login_required
def checkout(request):
    if request.method == 'GET':
        context = dict()
        customer = request.user
        addresses = Address.objects.filter(customer=customer)
        basket = request.session.get('basket')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in basket.items()])

        context['total_price'] = total_price
        context['addresses'] = addresses
        return render(request, 'orders/checkout.html', context)

    print(request.POST)
    # If the user has an address registered in the database and uses it to pay an order
    if 'address_id' in request.POST:
        basket = request.session.get('basket')
        delivery_method = request.POST.get('delivery_method')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in
             basket.items()]).amount

        if delivery_method == 'standard':
            total_price = total_price
        elif delivery_method == 'expedited':
            total_price += 15
        elif delivery_method == 'priority':
            total_price += 30

        customer = request.user
        address = Address.objects.get(id=request.POST.get('address_id'))

        # If user have an offer code
        if request.POST.get('offer_code'):
            discount = Discount.objects.get(code=request.POST.get('offer_code'))
            total_price_with_discount = (total_price * int(discount.amount)) / 100
            total_price_with_discount = total_price - total_price_with_discount
        else:
            discount = None
            total_price_with_discount = total_price

        order = Order(
            customer=customer,
            address=address,
            delivery_method=delivery_method,
            total_price=total_price,
            discount=discount,
            total_price_with_discount=total_price_with_discount
        )
        order.save()

        [order.products.create(product_name=product_name, quantity=quantity) for product_name, quantity in
         basket.items()]

        # Reduce the number of available products in stock
        [Product.objects.filter(name=product_name).update(number_of_product=F('number_of_product') - int(quantity)) for
         product_name, quantity in basket.items()]

        del request.session['basket']
        return render(request, 'orders/checkout_complete.html')

    # If the user has no address registered in the database
    elif 'address' in request.POST:
        basket = request.session.get('basket')
        delivery_method = request.POST.get('delivery_method')
        total_price = sum(
            [Product.objects.get(name=product_name).price * quantity for product_name, quantity in
             basket.items()]).amount

        if delivery_method == 'standard':
            total_price = total_price
        elif delivery_method == 'expedited':
            total_price += 15
        elif delivery_method == 'priority':
            total_price += 30

        customer = request.user

        # Create a new address and use it in the payment
        # Default address type is HOME

        new_address = Address(
            customer=customer,
            address=request.POST.get('address'),
            country=request.POST.get('country'),
            city=request.POST.get('city'),
            state=request.POST.get('state'),
            postcode=request.POST.get('postcode'),

        )
        new_address.save()
        # If user have an offer code
        if request.POST.get('offer_code'):
            discount = Discount.objects.get(code=request.POST.get('offer_code'))
            total_price_with_discount = (total_price * int(discount.amount)) / 100
            total_price_with_discount = total_price - total_price_with_discount
        else:
            discount = None
            total_price_with_discount = total_price

        order = Order(
            customer=customer,
            address=new_address,
            delivery_method=delivery_method,
            total_price=total_price,
            discount=discount,
            total_price_with_discount=total_price_with_discount
        )
        order.save()

        [order.products.create(product_name=product_name, quantity=quantity) for product_name, quantity in
         basket.items()]

        # Reduce the number of available products in stock
        [Product.objects.filter(name=product_name).update(number_of_product=F('number_of_product') - int(quantity)) for
         product_name, quantity in basket.items()]

        del request.session['basket']
        return render(request, 'orders/checkout_complete.html')

orders/templates/orders/checkout.html
{% extends 'products/base.html' %}
{% load subtotal %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}


    {#Start mini nav#}
    <div class="col-xl-12 d-flex justify-content-center">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:addresses' %}">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>
    {#End mini nav#}


    {#    Start checkout#}

    <div class="col-12">


        <form action="{% url 'orders:checkout' %}" method="post">
            {% csrf_token %}

            <div class="col-12 d-flex justify-content-center">
                <div class="col-6 d-flex justify-content-center"><input type="text" id="offerCode"
                                                                        placeholder="Offer code?" name="offer_code">
                </div>
                <div class="col-6 d-flex justify-content-center">
                    <button class="btn btn-danger btn-sm applyBtn" type="button">Apply</button>
                </div>
            </div>

            <div class="col-12 d-flex justify-content-center mt-5">
                <div class="col-6 d-flex justify-content-center">
                    <p>
                        <mark class="paymentMark">Total Price : {{ total_price }}</mark>
                    </p>
                </div>
                <div class="col-6  d-flex justify-content-center">
                    <p>
                        <mark class="paymentMark">Products in basket : {{ request.session.basket | length }}</mark>
                    </p>
                </div>
            </div>

            {% if addresses|length > 0 %}
                <div class="col-12 d-flex justify-content-center mt-4">
                    <div class="col-12 d-flex justify-content-center">
                        {% for address in addresses %}
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="address_id"
                                       id="{{ address.id }}" value="{{ address.id }}" required>
                                <label class="form-check-label" for="{{ address.id }}">
                                    {{ address }}
                                </label>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                {#If the user did not have an address registered in the database#}
            {% else %}

                <div class="col-xl-10 d-flex justify-content-center" id="error"></div>

                <div class="row">
                    <div class="col-xl-12">
                        <div class="form-group"><label for="id_address">Address</label><input type="text"
                                                                                              name="address"
                                                                                              maxlength="1024"
                                                                                              class="form-control"
                                                                                              placeholder="Address"
                                                                                              title=""
                                                                                              required=""
                                                                                              id="id_address">
                        </div>
                    </div>

                    <div class="col-xl-6">
                        <div class="form-group"><label for="id_country">Country</label><input type="text"
                                                                                              name="country"
                                                                                              maxlength="3"
                                                                                              class="form-control"
                                                                                              placeholder="Country"
                                                                                              title=""
                                                                                              required=""
                                                                                              id="id_country">
                        </div>
                    </div>

                    <div class="col-xl-6">
                        <div class="form-group"><label for="id_city">City</label><input type="text"
                                                                                        name="city"
                                                                                        maxlength="150"
                                                                                        class="form-control"
                                                                                        placeholder="City"
                                                                                        title="" required=""
                                                                                        id="id_city"></div>
                    </div>

                    <div class="col-xl-6">
                        <div class="form-group"><label for="id_state">State</label><input type="text"
                                                                                          name="state"
                                                                                          maxlength="150"
                                                                                          class="form-control"
                                                                                          placeholder="State"
                                                                                          title=""
                                                                                          required=""
                                                                                          id="id_state">
                        </div>
                    </div>

                    <div class="col-xl-6">
                        <div class="form-group"><label for="id_postcode">Postcode</label><input type="text"
                                                                                                name="postcode"
                                                                                                maxlength="12"
                                                                                                class="form-control"
                                                                                                placeholder="Postcode"
                                                                                                title=""
                                                                                                required=""
                                                                                                id="id_postcode">
                        </div>
                    </div>

                    <div class="col-xl-12 d-flex justify-content-center mt-10">

                    </div>
                </div>


            {% endif %}

            {#        Start Delivery Speed#}
            <div class="col-12 d-flex justify-content-center mt-4">

                <p>
                    Delivery method
                </p>
            </div>
            <div class="col-12 d-flex justify-content-center mt-4">

                <div class="col-8 d-flex justify-content-center">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="delivery_method" id="standard"
                               value="standard" required>
                        <label class="form-check-label" for="standard">Standard</label>
                    </div>

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="delivery_method" id="expedited"
                               value="expedited">
                        <label class="form-check-label" for="expedited">Expedited (Total price + $15)</label>
                    </div>

                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="delivery_method" id="priority"
                               value="priority">
                        <label class="form-check-label" for="priority">Priority (Total price + $30)</label>
                    </div>
                </div>
            </div>
            {#End Delivery Speed#}

            <div class="col-12 d-flex justify-content-center mt-4">
                <div class="col-2 d-flex justify-content-center">
                    <button class="btn btn-primary  mb-4 customButtons" type="submit">PAY</button>
                </div>
            </div>
        </form>

    </div>
{% endblock %}

orders/templates/orders/checkout_complete.html
{% extends 'products/base.html' %}
{% load subtotal %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}
    {#Start mini nav#}
    <div class="col-xl-12 d-flex justify-content-center">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:addresses' %}">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>
    {#End mini nav#}


    <div class="col-12 d-flex justify-content-center">
        <div class="col-6 d-flex justify-content-center mt-5 mb-5">
            <h6>Thank you for buying and trusting our site.
                Order details will be sent to you via email.

            </h6>
        </div>
    </div>
{% endblock %}