accounts/urls.py
from django.urls import path
from .views import (
    SignUpView, SigninView,
    logout_view, customer_profile_view,
    OrdersView, order_items_view,
    addresses_view, ChangePasswordView,
    DeleteUserAddress,
)

app_name = 'accounts'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SigninView.as_view(), name='sign_in'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('logout/', logout_view, name='logout'),
    path('profile/', customer_profile_view, name='profile'),
    path('addresses/', addresses_view, name='addresses'),
    path('delete_address/<int:pk>/', DeleteUserAddress.as_view(), name='delete_address'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order_items/<int:order_id>/', order_items_view, name='order_items'),

]

orders/api/urls.py
from django.urls import path
from .views import offer_code_api_view

urlpatterns = [
    path('offer_code/', offer_code_api_view, name='offer_code_api'),
]

orders/urls.py
from django.urls import path

from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'orders'

urlpatterns = [
    path('basket/', basket_view, name='basket'),
    path('basket/delete/', delete_item_from_basket, name='delete_item_from_basket'),
    path('checkout/', checkout, name='checkout'),
]

shopify/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shopify import settings
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, )

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social_django.urls', namespace='social')),

    path('api/v1/', include('core.api.urls')),
    path('', include('products.urls')),
    path('customer/', include('accounts.urls', namespace='customers')),
    path('order/', include('orders.urls')),

    # Django urls for reset password
    path('password_reset/',
         PasswordResetView.as_view(template_name='customers/password_reset.html'),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='customers/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='customers/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(template_name='customers/password_reset_complete.html'),
         name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator

from shopify import settings


class Customer(AbstractUser):
    phone_number_regex = RegexValidator(regex=r"^\+?1?\d{8,15}$", message=_('Must enter a valid phone number'))
    phone_number = models.CharField(validators=[phone_number_regex], max_length=16, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = _("customers")
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        return f'{self.first_name}{self.last_name}'


class Address(models.Model):
    HOME = 'home'
    OFFICE = 'office'
    OTHER = 'other'
    ADDRESS_TYPE = [(HOME, _('Home')), (OFFICE, _('Office')), (OTHER, _('Other')), ]

    # Users can have one or many addresses
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(_("Address"), max_length=1024, )
    country = models.CharField(_("Country"), max_length=30, )
    state = models.CharField(_("State"), max_length=150, )
    city = models.CharField(_("City"), max_length=150, )
    postcode = models.CharField(_("Postcode"), max_length=12, )
    address_type = models.CharField(max_length=6, choices=ADDRESS_TYPE, default=HOME)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    class Meta:
        db_table = _("addresses")
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

    def __str__(self):
        return f'{self.address}'

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from shopify import settings
from accounts.models import Address
from products.models import Product
from djmoney.models.fields import MoneyField


class Discount(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True,
                                 related_name='discounts')
    created = models.DateTimeField(auto_now_add=True)
    expire_date = models.DateTimeField()
    amount = models.PositiveSmallIntegerField()
    code = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = _('discounts')
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')

    def __str__(self):
        return f'{self.customer} {self.amount}%'


class OrderItem(models.Model):
    product_name = models.CharField(max_length=150)
    quantity = models.SmallIntegerField()

    class Meta:
        db_table = _('order_item ')
        verbose_name = _('Order item')
        verbose_name_plural = _('Order items')

    def __str__(self):
        return f'{self.product_name}'


class Order(models.Model):
    READY_TO_SHIP = 'ready_to_ship'
    SENDING = 'sending'
    SENT = 'sent'
    STATUS = [
        (READY_TO_SHIP, _('ready_to_ship')),
        (SENDING, _('sending')),
        (SENT, _('sent')),
    ]

    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='orders')
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    products = models.ManyToManyField(OrderItem)
    status = models.CharField(
        max_length=15,
        choices=STATUS,
        default=READY_TO_SHIP,
    )
    delivery_method = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    discount = models.OneToOneField(Discount, on_delete=models.RESTRICT, null=True, blank=True)
    total_price_with_discount = MoneyField(max_digits=10, decimal_places=2, default_currency='USD', blank=True,
                                           null=True)

    class Meta:
        db_table = _('orders')
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'{self.customer}'

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from .models import Customer, Address


class SignUpForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ['username', 'password', ]


SignUpForm = SignUpForm


class SignInForm(AuthenticationForm):
    class Meta:
        model = Customer


class ChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput())
    new_password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput())
    new_password_check = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput())

    class Meta:
        model = Customer
        fields = ['password', 'new_password', 'new_password_check', ]


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email', 'phone_number', ]


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['customer', 'created_at', 'updated_at', 'is_default']

accounts/api/views.py
from rest_framework.generics import CreateAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated
from .serializers import (SignUpSerializer, ChangePasswordSerializer, )
from accounts.models import Customer
from rest_framework import status
from rest_framework.response import Response


class SignUpView(CreateAPIView):
    """
        Provides the possibility of registration
    """
    serializer_class = SignUpSerializer


class ChangePasswordView(UpdateAPIView):
    """
    An endpoint for changing password.
    """
    serializer_class = ChangePasswordSerializer
    model = Customer
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):

        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Checking old password
            if not self.object.check_password(serializer.validated_data['password']):
                return Response({"password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)

            # Checking new password length
            elif len(serializer.validated_data['new_password']) < 8:
                return Response({"new_password": ["Your password must be at least 8 characters long."]},
                                status=status.HTTP_400_BAD_REQUEST)
            # Checking new password and new password check

            elif serializer.validated_data['new_password'] != serializer.validated_data['new_password_check']:
                return Response({"passwords": ["New password and New password check must match."]},
                                status=status.HTTP_400_BAD_REQUEST)

            # If no error occurs, the password will be updated
            self.object.set_password(serializer.validated_data['new_password'])
            self.object.save()

            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView, ListView, DeleteView

from accounts.forms import (
    SignUpForm, SignInForm,
    CustomerProfileForm,
    ChangePasswordForm,
    AddressForm,
)
from accounts.models import Address
from orders.models import Order
from products.models import Product


class SignUpView(FormView):
    form_class = SignUpForm
    template_name = 'customers/sign_up.html'


class SigninView(LoginView):
    authentication_form = SignInForm
    redirect_field_name = 'next'
    template_name = 'customers/sign_in.html'
    redirect_authenticated_user = True


class ChangePasswordView(LoginRequiredMixin, FormView):
    form_class = ChangePasswordForm
    template_name = 'customers/change_password.html'


@login_required
def customer_profile_view(request):
    if request.method == 'GET':

        context = dict()
        context['form'] = CustomerProfileForm(instance=request.user)
        return render(request, 'customers/customer_profile.html', context)

    elif request.method == 'POST':

        form = CustomerProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            context = dict()
            context['form'] = CustomerProfileForm(instance=request.user)
            messages.success(request, _('Profile details updated successfully.'))
            return render(request, 'customers/customer_profile.html', context)

        return HttpResponse('Form invalid', form.errors)


@login_required
def addresses_view(request):
    context = dict()
    user_addresses_in_database = Address.objects.filter(customer=request.user)
    context['form'] = AddressForm()
    context['addresses'] = user_addresses_in_database

    if request.method == 'GET':
        return render(request, 'customers/addresses.html', context)

    else:
        address_form = AddressForm(request.POST)

        if address_form.is_valid():
            obj, created = Address.objects.update_or_create(

                # Get address if exist
                id=request.POST.get('address_id'),

                # Create or update address
                defaults={'customer': request.user,
                          'address': address_form.cleaned_data['address'],
                          'country': address_form.cleaned_data['country'],
                          'state': address_form.cleaned_data['state'],
                          'city': address_form.cleaned_data['city'],
                          'postcode': address_form.cleaned_data['postcode'],
                          'address_type': address_form.cleaned_data['address_type'],
                          },
            )

            if created:
                messages.success(request, 'Your address has been saved.')
            else:
                messages.success(request, 'Your address successfully updated.')

            return render(request, 'customers/addresses.html', context)

        messages.error(request, 'Form is invalid.')
        return render(request, 'customers/addresses.html', context)


class DeleteUserAddress(DeleteView):
    model = Address
    success_url = reverse_lazy('customers:addresses')


class OrdersView(LoginRequiredMixin, ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'customers/orders.html'

    def get_queryset(self):
        queryset = super(OrdersView, self).get_queryset()
        queryset = queryset.filter(customer=self.request.user)
        return queryset


@login_required
def order_items_view(request, order_id):
    if request.method == 'GET':
        context = dict()
        order = Order.objects.get(id=order_id).products.all()
        order_products = [Product.objects.get(name=product_name) for product_name in order]
        context['order'] = order
        context['order_product'] = order_products
        return render(request, 'customers/order_items.html', context)


def logout_view(request):
    logout(request)
    return redirect('products:index')

orders/api/views.py
from django.utils.timezone import now
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from orders.models import Discount


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def offer_code_api_view(request):
    if request.method == 'POST':
        offer_code = request.POST.get('offerCode')
        customer = request.user
        try:
            discount = Discount.objects.get(code=offer_code)

            if discount.is_active and discount.expire_date > now() and discount.customer == customer:
                content = {'applied': 'Your discount code was applied correctly.',
                           'amount': discount.amount}
                discount.is_active = False
                discount.save()
                return Response(content, status=status.HTTP_200_OK)

            elif not discount.is_active:
                content = {'used': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

            elif discount.expire_date < now():
                content = {'expired': 'Your discount code has been used.'}
                return Response(content, status=status.HTTP_404_NOT_FOUND)

        except Discount.DoesNotExist:
            content = {'incorrect offer code': 'Your offer code is incorrect.'}
            return Response(content, status=status.HTTP_404_NOT_FOUND)

accounts/templates/customers/addresses.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}


    {#Start mini nav#}
    <div class="col-xl-12 d-flex justify-content-center">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>
    {#End mini nav#}


    {#    Addresses table#}
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">Country</th>
            <th scope="col">State</th>
            <th scope="col">City</th>
            <th scope="col">Postcode</th>
            <th scope="col">Address</th>
            <th scope="col">Address</th>
            <th scope="col"></th>
            <th scope="col"></th>


        </tr>
        </thead>
        <tbody>
        {% for address in addresses %}
            <tr>
                <form id="addressForm" method="post" action="{% url 'customers:addresses' %}">
                    {% csrf_token %}

                    <th scope="row">{{ address.count }}</th>

                    <input type="hidden" name="address_id" value="{{ address.id }}">

                    <td class="countryTd">
                        <input type="text" name="country" maxlength="3" class="form-control"
                               placeholder="{{ address.country }}"
                               title="" required="" id="id_country">
                    </td>


                    <td><input type="text" name="state" maxlength="150" class="form-control"
                               placeholder="{{ address.state }}"
                               title="" required="" id="id_state"></td>

                    <td>
                        <input type="text" name="city" maxlength="150" class="form-control"
                               placeholder="{{ address.city }}" title=""
                               required="" id="id_city">
                    </td>

                    <td>
                        <input type="text" name="postcode" maxlength="12" class="form-control"
                               placeholder={{ address.postcode }}
                                       title="" required="" id="id_postcode">
                    </td>

                    <td><input type="text" name="address" maxlength="1024" class="form-control"
                               placeholder="{{ address.address }}"
                               title="" required="" id="id_address"></td>

                    <td>

                        <select name="address_type" class="form-control" title="" id="id_address_type">

                            {% if address.address_type == 'other' %}

                                <option value="other" selected="">Other</option>
                                <option value="home">Home</option>
                                <option value="office">Office</option>

                            {% elif address.address_type == 'office' %}

                                <option value="office" selected="">Office</option>
                                <option value="home">Home</option>
                                <option value="other">Other</option>

                            {% else %}

                                <option value="home" selected="">Home</option>
                                <option value="office">Office</option>
                                <option value="other">Other</option>

                            {% endif %}

                        </select>

                    </td>

                    <td>
                        <button class="btn btn-primary btn-sm" type="submit">
                            UPDATE
                        </button>
                    </td>
                </form>

                {#            Delete address#}
                <form id="addressForm" method="post" action="{% url 'customers:delete_address' address.id %}">
                    {% csrf_token %}
                    <td>
                        <button class="btn btn-danger btn-sm" type="submit">
                            DELETE
                        </button>
                    </td>
                </form>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    {#End addresses table#}


    {#    Address form #}
    {#    The user can have 3 addresses#}
    {% if addresses|length >= 3 %}

        {% if messages %}

            {% for message in messages %}

                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-primary d-flex justify-content-center" role="alert">
                        {{ message }}
                    </div>

                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                    <div class="alert alert-danger d-flex justify-content-center" role="alert">
                        {{ message }}
                    </div>

                {% endif %}

            {% endfor %}
        {% endif %}


    {% else %}
        <div class="row d-flex justify-content-center">
            <div class="col-lg-8 d-flex justify-content-center">

                <form id="addressForm" method="post" action="{% url 'customers:addresses' %}">
                    {% csrf_token %}
                    {% if messages %}

                        {% for message in messages %}

                            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                                <div class="alert alert-primary d-flex justify-content-center" role="alert">
                                    {{ message }}
                                </div>

                            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                                <div class="alert alert-danger d-flex justify-content-center" role="alert">
                                    {{ message }}
                                </div>

                            {% endif %}

                        {% endfor %}
                    {% endif %}



                    <div class="col-xl-10 d-flex justify-content-center" id="error"></div>

                    <div class="row">

                        <div class="col-xl-12">
                            {% bootstrap_field form.address show_label=True %}
                        </div>

                        <div class="col-xl-6">
                            {% bootstrap_field form.country show_label=True %}
                        </div>

                        <div class="col-xl-6">
                            {% bootstrap_field form.city show_label=True %}
                        </div>

                        <div class="col-xl-6">
                            {% bootstrap_field form.state show_label=True %}
                        </div>

                        <div class="col-xl-6">
                            {% bootstrap_field form.postcode show_label=True %}
                        </div>

                        <div class="col-xl-12">
                            {% bootstrap_field form.address_type show_label=True %}
                        </div>

                        <div class="col-xl-12 d-flex justify-content-center mt-10">

                            <div class="col-lg-4 ">
                                <button id="saveAddressBtn" type="submit" class="customButtons btn btn-dark ">Save
                                    address
                                </button>
                            </div>

                        </div>
                    </div>

                </form>

            </div>
        </div>
    {% endif %}

    {#    End address form#}

{% endblock %}

accounts/templates/customers/customer_profile.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}

    <div class="col-xl-12 d-flex justify-content-center">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:addresses' %}">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>



    {#start user details form    #}
    <div class="col-xl-12 d-flex justify-content-center">

        <form action="{% url 'customers:profile' %}" method="POST">
            {% csrf_token %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-primary" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="col-xl-12">

                {% bootstrap_field form.first_name show_label=True %}<br>
            </div>

            <div class="col-xl-12">

                {% bootstrap_field form.last_name show_label=True %}<br>
            </div>

            <div class="col-xl-12">
                {% bootstrap_field form.email show_label=True %}<br>
            </div>

            <div class="col-xl-12">
                {% bootstrap_field form.phone_number show_label=True %}<br>
            </div>

            <button type="submit" class="customButtons btn btn-dark ">Save changes</button>

        </form>

    </div>
    {#end user details form#}
{% endblock %}

accounts/templates/customers/order_items.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}

    {#Start mini nav#}
    <div class="col-xl-12 d-flex justify-content-center">
        <nav class="navbar navbar-expand-lg ">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:profile' %}">Porofile</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:orders' %}">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:addresses' %}">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:change_password' %}">Change
                                Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link profile-link" href="{% url 'customers:logout' %}">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr>
    {#End mini nav#}

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col">IMAGE</th>
            <th scope="col">NAME</th>
            <th scope="col">PRICE</th>
            <th scope="col">QUANTITY</th>

        </tr>
        </thead>
        <tbody>

        {% for product in order_product %}
            <tr>
                <th scope="row">{{ product.count }}</th>
                <td><img class="productImage" src="/media/{{ product.image }}" alt="product_image"/></td>
                <td>{{ product.name }}</td>
                <td>{{ product.price }}</td>
                {% for item in order %}

                    {% if product.name == item.product_name %}
                        <td>{{ item.quantity }}</td>
                    {% endif %}
                {% endfor %}
            </tr>


        {% endfor %}

        </tbody>
    </table>


{% endblock %}

accounts/templates/customers/password_reset.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}
    {#    Email reset form start#}
    <div class="col-xl-12 d-flex justify-content-center">

        <form method="post">
            <div class="col-xl-12 d-flex justify-content-center">
                <h3>Password reset</h3>
            </div>
            <p>
                Enter your email address below, and we’ll email instructions for setting a new one.
            </p>
            {% csrf_token %}
            <div class="col-xl-12 ">
                {% bootstrap_form form show_label=False %}<br>
            </div>
            <div class="col-xl-12 d-flex justify-content-center">
                <div class="col-xl-4">
                    <button type="submit" class="customButtons btn btn-dark ">Send email</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

accounts/templates/customers/password_reset_complete.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}
{% bootstrap_field form %}

{% block content %}

    <div class="col-xl-12 d-flex justify-content-center">
        <h3>Password reset complete</h3><br><br><br>

    </div>
    <div class="col-xl-12 d-flex justify-content-center">

        <p>
            Your password has been set. You may go ahead and log in now.
        </p>
    </div>
{% endblock %}