accounts/urls.py
from django.urls import path
from .views import (
    SignUpView, SigninView,
    logout_view, customer_profile_view,
    OrdersView, order_items_view,
    addresses_view, ChangePasswordView,
    DeleteUserAddress,
)

app_name = 'accounts'

urlpatterns = [
    path('sign_up/', SignUpView.as_view(), name='sign_up'),
    path('sign_in/', SigninView.as_view(), name='sign_in'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('logout/', logout_view, name='logout'),
    path('profile/', customer_profile_view, name='profile'),
    path('addresses/', addresses_view, name='addresses'),
    path('delete_address/<int:pk>/', DeleteUserAddress.as_view(), name='delete_address'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('order_items/<int:order_id>/', order_items_view, name='order_items'),

]

orders/urls.py
from django.urls import path

from orders.views import basket_view, delete_item_from_basket, checkout

app_name = 'orders'

urlpatterns = [
    path('basket/', basket_view, name='basket'),
    path('basket/delete/', delete_item_from_basket, name='delete_item_from_basket'),
    path('checkout/', checkout, name='checkout'),
]

products/api/urls.py
from django.urls import path
from .views import (CreateContactApi, ProductListApi)

urlpatterns = [
    path('contact/', CreateContactApi.as_view(), name='create_contact_api'),
    path('product_list/', ProductListApi.as_view(), name='product_list_api'),
]

products/urls.py
from django.urls import path
from .views import (IndexView, ShopView,
                    ProductDetail, product_by_category,
                    AboutView, ContactView)

app_name = 'products'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('products/<slug:slug>/', ProductDetail.as_view(), name='product_detail'),
    path('categories/<str:category>/', product_by_category, name='product_by_category'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

shopify/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shopify import settings
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView, )

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('social_django.urls', namespace='social')),

    path('api/v1/', include('core.api.urls')),
    path('', include('products.urls')),
    path('customer/', include('accounts.urls', namespace='customers')),
    path('order/', include('orders.urls')),

    # Django urls for reset password
    path('password_reset/',
         PasswordResetView.as_view(template_name='customers/password_reset.html'),
         name='password_reset'),

    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='customers/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='customers/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(template_name='customers/password_reset_complete.html'),
         name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, db_index=True, unique=True, blank=True, null=True, )
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = _('categories')
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        # Raise on circular reference
        parent = self.parent
        while parent is not None:
            if parent == self:
                raise RuntimeError("Circular references not allowed")
            parent = parent.parent

        super(Category, self).save(*args, **kwargs)

    @property
    def children(self):
        return self.category_set.all().order_by("title")


class Contact(models.Model):
    name = models.CharField(max_length=150, null=True, blank=True)
    email = models.EmailField(max_length=150, null=True, blank=True)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = _('contacts')
        verbose_name = _('Contact')
        verbose_name_plural = _('Contacts')

    def __str__(self):
        return f'{self.name}'


class IPaddress(models.Model):
    ip_address = models.GenericIPAddressField()

    class Meta:
        db_table = _('ip_addresses')
        verbose_name = _('ip_address')
        verbose_name_plural = _('IPaddress')

    def __str__(self):
        return f'{self.ip_address}'


class Product(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField()
    image = models.ImageField(upload_to='product_images')
    number_of_product = models.PositiveSmallIntegerField(blank=True, null=True)
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    views = models.ManyToManyField(IPaddress, blank=True)

    class Meta:
        db_table = _('products')
        verbose_name = _('Product')
        verbose_name_plural = _('Products')
        ordering = ['-created']

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})

products/api/views.py
from rest_framework.generics import (CreateAPIView,
                                     ListAPIView, )
from .serializers import ContactSerializer, ProductListSerializer
from rest_framework.pagination import PageNumberPagination
from ..models import Product


class CreateContactApi(CreateAPIView):
    serializer_class = ContactSerializer


class ProductListApi(ListAPIView):
    queryset = Product.objects.filter(is_active=True)
    serializer_class = ProductListSerializer
    pagination_class = PageNumberPagination

    def get_queryset(self):
        queryset = Product.objects.filter(is_active=True)
        category = self.request.query_params.get('category')
        if category is not None:
            queryset = queryset.filter(category__name=category)
        return queryset

products/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.views.generic import ListView,DetailView,TemplateView


class IndexView(ListView):
    model = Product

    # 3 of the most visited products
    queryset = (Product.objects.filter(is_active=True, in_stock=True).annotate(product_view=Count('views')).order_by(
        '-product_view')[:3])

    context_object_name = 'products'
    template_name = 'products/index.html'

    # 5 of the latest products
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['latest'] = Product.objects.filter(is_active=True, in_stock=True).order_by('-created')[:5]
        return context


class ShopView(ListView):
    model = Product
    queryset = Product.objects.filter(is_active=True, in_stock=True).order_by('-created')[:9]
    context_object_name = 'products'
    template_name = 'products/shop.html'

    def get_context_data(self, **kwargs):
        context = super(ShopView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(is_active=True)
        return context


class ProductDetail(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'products/product_detail.html'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        product = get_object_or_404(Product, slug=slug)
        return product


def product_by_category(request, category):
    context = dict()
    category_id = Category.objects.get(name=category).id
    categories = Category.objects.filter(is_active=True)
    product_list = Product.objects.filter(category=category_id, is_active=True, in_stock=True)
    context['products'] = product_list
    context['categories'] = categories
    return render(request, 'products/product_by_category.html', context=context)


class AboutView(TemplateView):
    template_name = 'products/about.html'


class ContactView(TemplateView):
    template_name = 'products/contact.html'

products/templates/products/base.html
{% load static %} {#<!DOCTYPE html>#}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="apple-touch-icon" href="/media/siteImages/apple-icon.png" />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="/media/siteImages/favicon.ico"
    />

    <link
      rel="stylesheet"
      href="{% static 'products/css/bootstrap.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'products/css/templatemo.css' %}" />
    <link rel="stylesheet" href="{% static 'products/css/custom.css' %}" />

    <!-- Load fonts style after rendering the layout styles -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap"
    />
    <link
      rel="stylesheet"
      href="{% static 'products/css/fontawesome.min.css' %}"
    />
    {% block css %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
      <div class="container d-flex justify-content-between align-items-center">
        <a
          class="navbar-brand text-primary logo h1 align-self-center"
          href="{% url 'products:index' %}"
        >
          Shopify
        </a>

        <button
          class="navbar-toggler border-0"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#templatemo_main_nav"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="
            align-self-center
            collapse
            navbar-collapse
            flex-fill
            d-lg-flex
            justify-content-lg-between
          "
          id="templatemo_main_nav"
        >
          <div class="flex-fill">
            <ul
              class="nav navbar-nav d-flex justify-content-between mx-lg-auto"
            >
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:shop' %}">Shop</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:contact' %}"
                  >Contact</a
                >
              </li>
            </ul>
          </div>
          <div class="navbar align-self-center d-flex">
            <div
              class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3"
            >
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  id="inputMobileSearch"
                  placeholder="Search ..."
                />
                <div class="input-group-text">
                  <i class="fa fa-fw fa-search"></i>
                </div>
              </div>
            </div>

            <a
              class="nav-icon d-none d-lg-inline"
              href="#"
              data-bs-toggle="modal"
              data-bs-target="#templatemo_search"
            >
              <i class="fa fa-fw fa-search text-dark mr-2"></i>
            </a>

            <a
              class="nav-icon position-relative text-decoration-none"
              href="{% url 'orders:basket' %}"
            >
              <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>
              <span
                id="basketBadge"
                class="
                  position-absolute
                  top-0
                  left-100
                  translate-middle
                  badge
                  rounded-pill
                  bg-light
                  text-dark
                "
              ></span>
            </a>

            <a class="nav-icon position-relative text-decoration-none" href="#">
              <a href="{% url 'customers:sign_in' %}"
                ><i class="fa fa-fw fa-user text-dark mr-3"></i
              ></a>
              <span
                class="
                  position-absolute
                  top-0
                  left-100
                  translate-middle
                  badge
                  rounded-pill
                  bg-light
                  text-dark
                "
              ></span>
            </a>
          </div>
        </div>
      </div>
    </nav>
    <!-- Close Header -->

    <!-- Modal -->
    <div
      class="modal fade bg-white"
      id="templatemo_search"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-lg" role="document">
        <div class="w-100 pt-1 mb-5 text-right">
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <form
          action=""
          method="get"
          class="modal-content modal-body border-0 p-0"
        >
          <div class="input-group mb-2">
            <input
              type="text"
              class="form-control"
              id="inputModalSearch"
              name="q"
              placeholder="Search ..."
            />
            <button
              type="submit"
              class="input-group-text bg-primary text-light"
            >
              <i class="fa fa-fw fa-search text-white"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
    <!-- end Modal -->

    {% block content %}{% endblock %}

    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 pt-5">
            <h2 class="h2 text-primary border-bottom pb-3 border-light logo">
              Shopify
            </h2>
            <ul class="list-unstyled text-light footer-link-list">
              <li>
                <i class="fa fa-envelope fa-fw"></i>
                <a
                  class="text-decoration-none"
                  href="mailto:mobin.agaei@gmail.com"
                  >mobin.agaei@gmail.com</a
                >
              </li>
              <li>
                <i class="fa fa-phone fa-fw"></i>
                <a class="text-decoration-none" href="tel:+98-990-955-7388"
                  >+98 990 955 73 88</a
                >
              </li>

              <li>
                <i class="fas fa-map-marker-alt fa-fw"></i>
                <a
                  class="text-decoration-none"
                  href="https://www.google.com/maps/place/%D8%A7%D8%B1%D8%AF%D8%A8%DB%8C%D9%84%D8%8C+%D8%A7%D8%B3%D8%AA%D8%A7%D9%86+%D8%A7%D8%B1%D8%AF%D8%A8%DB%8C%D9%84%D8%8C+%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%E2%80%AD/@38.2668309,48.4110735,12z/data=!3m1!4b1!4m5!3m4!1s0x4018979ffdc9dca9:0xbe7e5e042fd87cba!8m2!3d38.2537514!4d48.3000183"
                  >Iran / Ardabil</a
                >
              </li>
            </ul>
          </div>

          <div class="col-md-4 pt-5">
            <h2 class="h2 text-primary border-bottom pb-3 border-light">
              Detail
            </h2>
            <ul class="list-unstyled text-light footer-link-list">
              <li>
                <p>
                  The Onlineshop is a virtual store on the Internet where
                  customers can browse the catalog and select products of
                  interest. The selected items may be collected in a shopping
                  cart.
                </p>
              </li>
            </ul>
          </div>

          <div class="col-md-4 pt-5">
            <h2 class="h2 text-primary border-bottom pb-3 border-light">
              Further Info
            </h2>
            <ul class="list-unstyled text-light footer-link-list">
              <li>
                <a
                  class="text-decoration-none"
                  href="{% url 'products:index' %}"
                  >Home</a
                >
              </li>
              <li>
                <a
                  class="text-decoration-none"
                  href="{% url 'products:about' %}"
                  >About Us</a
                >
              </li>
              <li>
                <a class="text-decoration-none" href="#">Shop Locations</a>
              </li>
              <li><a class="text-decoration-none" href="#">FAQs</a></li>
              <li>
                <a
                  class="text-decoration-none"
                  href="{% url 'products:contact' %}"
                  >Contact</a
                >
              </li>
            </ul>
          </div>
        </div>

        <div class="w-100 bg-black py-3">
          <div class="container">
            <div class="row pt-2">
              <div class="col-12">
                <p class="text-left text-light">
                  Copyright &copy; 2021 Shopify
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

    <!-- Start Script -->

    <script src="{% static 'products/js/jquery-1.11.0.min.js' %}"></script>
    <script src="{% static 'products/js/jquery-migrate-1.2.1.min.js' %}"></script>
    <script src="{% static 'products/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'products/js/templatemo.js' %}"></script>
    <script src="{% static 'products/js/custom.js' %}"></script>

    <script src="{% static 'customers/js.js' %}"></script>

    <!-- End Script -->
    {% block js %}{% endblock %}
  </body>
</html>

products/templates/products/index.html
{% extends 'products/base.html' %}

{% block content %}

    <!-- Start Featured Product -->
    <section class="bg-light">
        <div class="container py-5">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Most visited products</h1>


                </div>
            </div>
            <div class="row">

                {% for product in products %}

                    <div class="col-12 col-md-4 mb-4">
                        <div class="card h-100">
                            <a href="{% url 'products:product_detail' product.slug %}">
                                <img src="{{ product.image.url }}" class="card-img-top"
                                     alt="feature_prod_01">
                            </a>
                            <div class="card-body">
                                <ul class="list-unstyled d-flex justify-content-between">
                                    <li class=" text-right">{{ product.price }}</li>
                                </ul>
                                <a href="#"
                                   class="h2 text-decoration-none text-dark profile-link">{{ product.name }}</a><br>
                                <p class="card-text ">
                                    {{ product.description | slice:":100" }}...
                                </p>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>
    <!-- End Featured Product -->
{% endblock %}

products/templates/products/product_by_category.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}

{% block content %}

    <!-- Start Content -->
    <div class="container py-5">
        <div class="row">

            <div class="col-lg-3">
                <h1 class="h2 pb-4 text-primary">Categories</h1>
                {% for category in categories %}
                    <a class="collapsed d-flex justify-content-between h3 text-decoration-none profile-link"
                       href="{% url 'products:product_by_category' category.name %}">
                        {{ category }}
                    </a><br>
                {% endfor %}
            </div>

            <div class="col-lg-9">
                <div class="row">

                    <div class="col-md-6"></div>

                    <div class="col-md-6 pb-4">
                        <div class="d-flex">

                        </div>
                    </div>
                </div>


                <div class="row" id="productRow">

                    {% for product in products %}
                        <p id="categoryP" hidden>{{ product.category }}</p>
                        <div class="col-md-4">
                            <div class="card mb-4 product-wap rounded-0">
                                <div class="card rounded-0">
                                    <img class="card-img rounded-0 img-fluid" src="/media/{{ product.image }}"
                                         alt="{{ product.name }} Image">

                                    <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                        <ul class="list-unstyled">
                                            <li><a class="btn btn-primary text-white" href="shop-single.html"><i
                                                    class="far fa-heart"></i></a></li>
                                            <li><a class="btn btn-primary text-white mt-2"
                                                   href="{% url 'products:product_detail' product.slug %}"><i
                                                    class="far fa-eye"></i></a></li>
                                            <li><a class="btn btn-primary text-white mt-2" href="shop-single.html"><i
                                                    class="fas fa-cart-plus"></i></a></li>
                                        </ul>
                                    </div>
                                </div>

                                <div class="card-body">
                                    <a href="{% url 'products:product_detail' product.slug %}"
                                       class="h3 text-decoration-none">{{ product.name }}</a>
                                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                        <li class="pt-2">
                                            <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                        </li>
                                    </ul>
                                    <p class="text-center mb-0">{{ product.price }}</p>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>
                <div div="row">
                    <ul class="pagination pagination-lg justify-content-center">
                        <button id="loadMoreBtn" type="button" class="btn orderTableBtn">
                            <li class="page-item disabled"></li>
                            Load more
                        </button>
                    </ul>
                </div>
            </div>

        </div>
    </div>
    <!-- End Content -->

{% endblock %}

products/templates/products/shop.html
{% extends 'products/base.html' %}
{% load bootstrap4 %}
{% bootstrap_field field %}

{% block content %}
    <!-- Start Content -->
    <div class="container py-5">
        <div class="row">

            <div class="col-lg-3">
                <h1 class="h2 pb-4 text-primary">Categories</h1>

                {% for category in categories %}
                    <a class="collapsed d-flex justify-content-between h3 text-decoration-none profile-link"
                       href="{% url 'products:product_by_category' category.name %}">
                        {{ category }}
                    </a><br>
                {% endfor %}
            </div>

            <div class="col-lg-9">
                <div class="row">

                    <div class="col-md-12 d-flex justify-content-center"><h3>Latest Products</h3></div>

                </div>


                <div class="row">

                    {% for product in products %}

                        <div class="col-md-4">
                            <div class="card mb-4 product-wap rounded-0">
                                <div class="card rounded-0">
                                    <img class="card-img rounded-0 img-fluid" src="/media/{{ product.image }}"
                                         alt="{{ product.name }} Image">

                                    <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                        <ul class="list-unstyled">

                                            {#                                            Wish list#}
                                            <li><a class="btn btn-primary text-white"><i
                                                    class="far fa-heart"></i></a></li>

                                            {#                                            Product detail #}
                                            <li><a class="btn btn-primary text-white mt-2"
                                                   href="{% url 'products:product_detail' product.slug %}"><i
                                                    class="far fa-eye"></i></a></li>

                                            {#                                            Add to basket --- > product with quantity 1#}
                                            <form action="{% url 'orders:basket' %}" method="POST">
                                                {% csrf_token %}

                                                <input type="hidden" name="product_name" value="{{ product.name }}">
                                                <input type="hidden" name="product_quantity"
                                                       id="product_quantity"
                                                       value="1">

                                                <li>
                                                    <button type="submit" class="btn btn-primary text-white mt-2">
                                                        <i class="fas fa-cart-plus"></i>
                                                    </button>
                                                </li>
                                            </form>

                                        </ul>
                                    </div>
                                </div>

                                <div class="card-body">
                                    <a href="{% url 'products:product_detail' product.slug %}"
                                       class="h3 text-decoration-none">{{ product.name }}</a>
                                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                                        <li class="pt-2">
                                            <span class="product-color-dot color-dot-red float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-blue float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-black float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-light float-left rounded-circle ml-1"></span>
                                            <span class="product-color-dot color-dot-green float-left rounded-circle ml-1"></span>
                                        </li>
                                    </ul>
                                    <p class="text-center mb-0">{{ product.price }}</p>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                </div>

            </div>

        </div>
    </div>
    <!-- End Content -->
{% endblock %}